version: '3.8'
services:
  speedtest:
    depends_on:
      - influx
    image: barrycarey/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    volumes:
      - ./config/config.ini:/src/config.ini
    restart: always
    networks:
      - speedtest

  influx:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "influx:/var/lib/influxdb"
    networks:
      - speedtest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=speedtest
      - DOCKER_INFLUXDB_INIT_PASSWORD=speedtest1
      - DOCKER_INFLUXDB_INIT_ORG=covenantpella
      - DOCKER_INFLUXDB_INIT_BUCKET=speedtests
      - DOCKER_INFLUXDB_INIT_RETENTION=10w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=speedtest123!

volumes:
  influx:

networks:
  speedtest:
